name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # or the branch you want to deploy from

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Configure Docker
      run: gcloud auth configure-docker

    - name: Build Docker image
      run: docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/flask-api:${{ github.sha }} .

    - name: Push Docker image
      run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/flask-api:${{ github.sha }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy flask-api \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/flask-api:${{ github.sha }} \
          --platform managed \
          --region asia-southeast2 \
          --allow-unauthenticated
