name: Docker build and push

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin

    - name: Build Docker image
      run: |
        docker build -t sparklingdust/resume_chatbot:latest .

    - name: Push Docker image to Docker Hub
      run: |
        docker push sparklingdust/resume_chatbot:latest
